apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-deployment
spec:
  selector:
    matchLabels:
      app: cpu-stress
  replicas: 1
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: vish/stress
        args:
        - --cpu
        - "1"
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 200m

