apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-agent
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      containers:
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:latest
        args:
          - "--config=/etc/zabbix/zabbix_agent2.conf"
        volumeMounts:
        - name: zabbix-agent-config
          mountPath: "/etc/zabbix"
      volumes:
      - name: zabbix-agent-config
        configMap:
          name: zabbix-agent-config

