zabbixServer:
  enabled: true
  image:
    repository: zabbix/zabbix-server-pgsql
    tag: alpine-6.0-latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

zabbixWeb:
  enabled: true
  image:
    repository: zabbix/zabbix-web-nginx-pgsql
    tag: alpine-6.0-latest
  php:
    timezone: America/Sao_Paulo
  service:
    type: ClusterIP
    port: 80

zabbixWebService:
  enabled: false

zabbixAgent:
  enabled: false

postgresql:
  enabled: true
  auth:
    username: zabbix
    password: zabbix
    database: zabbix

ingress:
  enabled: false

