apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-stack-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'example-receiver'
      routes:
      - match:
          severity: warning
        receiver: 'example-receiver'
    receivers:
    - name: 'example-receiver'
      webhook_configs:
      - url: 'http://example-webhook-url.com'

