apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  endpoints:
  - port: metrics
    interval: 15s

