apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: httpbin
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  endpoints:
  - port: http 
    interval: 15s
    path: /metrics
