apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: default
spec:
  type: ClusterIP  # Use NodePort ou LoadBalancer se precisar acessar de fora do cluster
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: httpbin

