kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: aulathree
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 9090
        hostPort: 9090
        protocol: TCP
      - containerPort: 3000
        hostPort: 3000
        protocol: TCP 